webapp:
  image: "infracloudio/csvserver"
  container_name: csvserver
  ports:
    - 9393:9300
  volumes:
    - /root/Desktop/inputFile:/csvserver/inputdata
  environment:
    CSVSERVER_BORDER: Orange
